[2025-03-26T21:50:08.936+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_store_dag.run_fetch_store scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-03-26T21:50:08.940+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_store_dag.run_fetch_store scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-03-26T21:50:08.940+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-26T21:50:08.952+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_fetch_store> on 2023-01-01 00:00:00+00:00
[2025-03-26T21:50:08.956+0000] {standard_task_runner.py:57} INFO - Started process 57171 to run task
[2025-03-26T21:50:08.959+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_store_dag', 'run_fetch_store', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/fetch_store_dag.py', '--cfg-path', '/tmp/tmpykyag75r']
[2025-03-26T21:50:08.960+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask run_fetch_store
[2025-03-26T21:50:08.988+0000] {task_command.py:410} INFO - Running <TaskInstance: fetch_store_dag.run_fetch_store scheduled__2023-01-01T00:00:00+00:00 [running]> on host codespaces-d2646d
[2025-03-26T21:50:09.028+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_store_dag' AIRFLOW_CTX_TASK_ID='run_fetch_store' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2025-03-26T21:50:09.029+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-26T21:50:09.029+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /workspaces/Team-34/src/data/fetch_store.py']
[2025-03-26T21:50:09.038+0000] {subprocess.py:86} INFO - Output:
[2025-03-26T21:50:09.387+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-03-26T21:50:09.387+0000] {subprocess.py:93} INFO -   File "/workspaces/Team-34/src/data/fetch_store.py", line 11, in <module>
[2025-03-26T21:50:09.387+0000] {subprocess.py:93} INFO -     import schedule
[2025-03-26T21:50:09.387+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'schedule'
[2025-03-26T21:50:09.426+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-26T21:50:09.431+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/miniconda/envs/airflow-env/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-26T21:50:09.433+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_store_dag, task_id=run_fetch_store, execution_date=20230101T000000, start_date=20250326T215008, end_date=20250326T215009
[2025-03-26T21:50:09.444+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task run_fetch_store (Bash command failed. The command returned a non-zero exit code 1.; 57171)
[2025-03-26T21:50:09.453+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-03-26T21:50:09.461+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
